### ISSUE TITLE
Window dimensions are always reported as 400x400

### ISSUE THREAD

**Issue by Octogonapus** [Gnimuc/CImGui.jl#130]
`GetWindowSize()`, `GetWindowWidth()`, and `GetWindowHeight()` always report 400 regardless of the provided `window_size` to `render` and regardless of the true window size when resizing it at runtime. I could reproduce this by adding `@show CImGui.GetWindowWidth()` [here](https://github.com/Gnimuc/CImGui.jl/blob/9dddcf3fd59d36fbfbd74a4535c8e5202dd93532/demo/demo.jl#L51) on the latest master.

**Comment by JamesWrigley** [comment]
The problem is the position of the calls to `GetWindowSize()`, they (along with all other CImGui calls) have to be within a `Begin()`/`End()` block to work properly. If you put it outside of that then it looks like you get the window size of the default debug window:
![image](https://github.com/Gnimuc/CImGui.jl/assets/5361518/329c5de6-6254-45e2-aed4-15211a3e0ddb)

See for example: https://github.com/ocornut/imgui/issues/4404#issuecomment-894266498

If you put those calls within a window block then you should get the right sizes. Alternatively, if you're really looking for the GLFW window size you probably want `unsafe_load(GetIO().DisplaySize)`.

**Comment by Octogonapus** [comment]
Thank you!
