### ISSUE TITLE
Correct ImGUI Version?

### ISSUE THREAD

**Issue by Gilga** [Gnimuc/CImGui.jl#19]
Julia Version: 1.3.1

i got an error in the wrapper:
```
┌ Error: Error in drawGUI! exception =
│   exception = UndefVarError: igTreeAdvanceToLabelPos not defined
└ ...

Stacktrace:
 [1] TreeAdvanceToLabelPos() at ... \.julia\packages\CImGui\OGzct\src\wrapper.jl:1484
...
```
Do you use the correct ImGUI version?
I guess some functions are missing or deprecated.

**Comment by Gnimuc** [comment]
It has been removed since [1.72](https://github.com/ocornut/imgui/releases/tag/v1.72). We can either remove this API(force users to upgrade their code) or build libcimgui with [`IMGUI_DISABLE_OBSOLETE_FUNCTIONS=0`](https://github.com/JuliaPackaging/Yggdrasil/blob/dfc5d9580b5eee0dca7f52621e9a3b7e9478c13e/C/CImGui/bundled/wrapper/CMakeLists.txt#L14).
