### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by alenskorobogatova** [Gnimuc/CImGui.jl#64]
Memory leak when launching examples of the master branch of CImGui (launch occurs as described in the readme file)

**Comment by Gnimuc** [comment]
Which example?

**Comment by Gnimuc** [comment]
only on Windows? does the problem persist if you disable the docking and multi-viewport features?

**Comment by Gnimuc** [comment]
The leak is probably due to this line in the backend: https://github.com/JuliaImGui/ImGuiGLFWBackend.jl/blob/a005da40908b1d5b1335762ef0723bae570453f8/src/interface.jl#L207

The implementation assumes the C-managed `Ptr{ImGuiPlatformMonitor}` pointer is initilized as a `C_NULL`, so there is no need to manually free it on the Julia side before we fill up it with the new resources. I've checked the related IMGUI code before, but I might be wrong as well.

**Comment by Gnimuc** [comment]
Not `gc`-ed, but `free`-ed by C. As `platform_io` is an object managed by the C library, I guess the C++ code does something like:

```c
if platform_io.monitors_ptr
    delete[] platform_io.monitors_ptr
```

**Comment by sairus7** [comment]
But this is called only once - how can it cause constant memory increase inside rendering cycle? 

Can it be somehow related to this bug with arrays or pointers? https://github.com/wsphillips/ImPlot.jl/issues/23

**Comment by Gnimuc** [comment]
By memory leak, do you mean "memory constantly increasing when running the GUI window" or "memory is not released correctly after GUI window is closed". I would like to know whether the leak is on the C  side or the Julia side. A MWE example would be helpful here.

**Comment by sairus7** [comment]
Some effects:

- Without any windows open, memory increase in 1 minute: 270 MB -- 922 MB (~11 MB/sec).
- With some window (demo or metrics), memory increase in 1 minute: 270 MB -- 1180 MB (~15 MB/sec).
- Repeated runs of the this script from the same Julia console increases initial GUI process memory.

**Comment by Gnimuc** [comment]
Thanks for reporting the issue! I've just tagged a new version which should be released within a hour.
