### ISSUE TITLE
Method to disable/grey-out widgets?

### ISSUE THREAD

**Issue by ianshmean** [Gnimuc/CImGui.jl#7]
It seems that disabling/greying-out widgets to prevent user interaction in imgui itself isn't well implemented (see https://github.com/ocornut/imgui/issues/211), but I was wondering whether that functionality is somehow added/addable through CImGui.jl? 

Also, thanks for all the work on this package! It's been a delight to work with

**Comment by Gnimuc** [comment]
>  I was wondering whether that functionality is somehow added/addable through CImGui.jl?

It looks like this feature is already in ocornut's TODO list, it would be great if it could come into 1.70. Since CImGui.jl is just a wrapper and not able to provide additional internal features like this one, the only feasible way is to manually patch imgui and expose that API like what [CImGuiBuilder](https://github.com/Gnimuc/CImGuiBuilder/tree/master/wrapper) did here.

**Comment by ianshmean** [comment]
Great! Thanks for the example

I'll close this but if I come across any issues will reopen
